### DELETE /events/:id
DELETE http://localhost:8080/events/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NjY0MzI3ODgsInVzZXJJZCI6MX0.nEy9eLxsBo6pqlbZCMjVjEMbzJSjMYs6-q0fiRlTre0